name: Build and deploy Docker image to Azure Web App - DpaWeb

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push Docker image
              run: |
                  docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dpaweb:latest .
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dpaweb:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
                  client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

            - name: 'Deploy to Azure Web App'
              uses: azure/webapps-deploy@v2
              with:
                  app-name: 'DpaWeb'
                  images: '${{ secrets.DOCKER_HUB_USERNAME }}/dpaweb:latest'
